services:
  # File Storage Database
  - type: psql
    name: file-storage-database
    plan: free
    databases:
      - name: verapdfdb
    envVars:
      - key: POSTGRES_USER
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
      - key: POSTGRES_PASSWORD
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}

  # File Storage Service
  - type: web
    name: file-storage
    plan: free
    env:
      - key: LOCALSTORAGE_DATABASE_USERNAME
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
      - key: LOCALSTORAGE_DATABASE_PASSWORD
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
      - key: LOCALSTORAGE_DATABASE_DB
        value: verapdfdb
      - key: LOCALSTORAGE_DATABASE_HOST
        value: file-storage-database
      - key: LOCALSTORAGE_DATABASE_PORT
        value: "5432"
      - key: LOCALSTORAGE_DISK_MIN_SPACE_THRESHOLD
        value: ${LOCAL_STORAGE_SERVICE_DISK_MIN_SPACE_THRESHOLD:-5GB}
      - key: LOCALSTORAGE_MAX_FILE_SIZE
        value: 100MB
      - key: LOCALSTORAGE_MAX_REQUEST_SIZE
        value: 101MB
    dockerImage: ghcr.io/verapdf/verapdf_file-storage:latest
    envSpecificSettings:
      disk:
        size: 5GB

  # Job Service Database
  - type: psql
    name: job-service-database
    plan: free
    databases:
      - name: verapdfjobdb
    envVars:
      - key: POSTGRES_USER
        value: ${JOB_SERVICE_DATABASE_USER}
      - key: POSTGRES_PASSWORD
        value: ${JOB_SERVICE_DATABASE_PASSWORD}

  # Job Service
  - type: web
    name: job-service
    plan: free
    env:
      - key: JOBSERVICE_DATABASE_USERNAME
        value: ${JOB_SERVICE_DATABASE_USER}
      - key: JOBSERVICE_DATABASE_PASSWORD
        value: ${JOB_SERVICE_DATABASE_PASSWORD}
      - key: JOBSERVICE_DATABASE_DB
        value: verapdfjobdb
      - key: JOBSERVICE_DATABASE_HOST
        value: job-service-database
      - key: JOBSERVICE_DATABASE_PORT
        value: "5432"
      - key: AMQP_SERVER_HOST
        value: queue
      - key: AMQP_USER
        value: ${AMQP_SERVER_USER}
      - key: AMQP_PASSWORD
        value: ${AMQP_SERVER_PASSWORD}
      - key: AMQP_SERVER_CONCURRENCY
        value: "4"
      - key: AMQP_SERVER_MAX_CONCURRENCY
        value: "8"
      - key: AMQP_SERVER_SENDING_QUEUE_NAME
        value: requestQueue
      - key: AMQP_SERVER_SENDING_QUEUE_MAX_SIZE
        value: 2047MB
      - key: AMQP_SERVER_LISTENING_QUEUE_NAME
        value: replyQueue
      - key: AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE
        value: 2047MB
      - key: TASK_PROCESSING_LIMIT
        value: "2"
    dockerImage: ghcr.io/verapdf/verapdf_job
