blueprint:
  name: verapdf-stack
  services:
    - name: file-storage-database
      type: postgres
      version: 11.7
      env:
        POSTGRES_USER: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
        POSTGRES_PASSWORD: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
        POSTGRES_DB: verapdfdb
      persistentVolume:
        name: localstorage_database_data
        mountPath: /var/lib/postgresql/data
    - name: file-storage
      type: web
      env:
        LOCALSTORAGE_DATABASE_USERNAME: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
        LOCALSTORAGE_DATABASE_PASSWORD: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
        LOCALSTORAGE_DATABASE_DB: verapdfdb
        LOCALSTORAGE_DATABASE_HOST: file-storage-database
        LOCALSTORAGE_DATABASE_PORT: 5432
        LOCALSTORAGE_DISK_MIN_SPACE_THRESHOLD: ${LOCAL_STORAGE_SERVICE_DISK_MIN_SPACE_THRESHOLD:-5GB}
        LOCALSTORAGE_MAX_FILE_SIZE: 100MB
        LOCALSTORAGE_MAX_REQUEST_SIZE: 101MB
      dockerfilePath: ./Dockerfile  # Assuming you have a Dockerfile for file-storage
      persistentVolume:
        name: localstorage_server_files
        mountPath: /opt/verapdf/localstorageservice/files
    - name: job-service-database
      type: postgres
      version: 11.7
      env:
        POSTGRES_USER: ${JOB_SERVICE_DATABASE_USER}
        POSTGRES_PASSWORD: ${JOB_SERVICE_DATABASE_PASSWORD}
        POSTGRES_DB: verapdfjobdb
      persistentVolume:
        name: jobservice_database_data
        mountPath: /var/lib/postgresql/data
    - name: job-service
      type: web
      env:
        JOBSERVICE_DATABASE_USERNAME: ${JOB_SERVICE_DATABASE_USER}
        JOBSERVICE_DATABASE_PASSWORD: ${JOB_SERVICE_DATABASE_PASSWORD}
        JOBSERVICE_DATABASE_DB: verapdfjobdb
        JOBSERVICE_DATABASE_HOST: job-service-database
        JOBSERVICE_DATABASE_PORT: 5432
        AMQP_SERVER_HOST: queue
        AMQP_USER: ${AMQP_SERVER_USER}
        AMQP_PASSWORD: ${AMQP_SERVER_PASSWORD}
        AMQP_SERVER_CONCURRENCY: "4"
        AMQP_SERVER_MAX_CONCURRENCY: "8"
        AMQP_SERVER_SENDING_QUEUE_NAME: requestQueue
        AMQP_SERVER_SENDING_QUEUE_MAX_SIZE: 2047MB
        AMQP_SERVER_LISTENING_QUEUE_NAME: replyQueue
        AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE: 2047MB
        TASK_PROCESSING_LIMIT: "2"
      dockerfilePath: ./Dockerfile  # Assuming you have a Dockerfile for job-service
    - name: queue
      type: rabbitmq
      version: 3.8.3
      env:
        RABBITMQ_DEFAULT_USER: ${AMQP_SERVER_USER}
        RABBITMQ_DEFAULT_PASSWORD: ${AMQP_SERVER_PASSWORD}
      persistentVolume:
        name: rabbitmq_database_data
        mountPath: /var/lib/rabbitmq/
    - name: worker
      type: web
      env:
        JVM_OPTS: ${WORKER_JVM_OPTS}
        AMQP_SERVER_HOST: queue
        AMQP_USER: ${AMQP_SERVER_USER}
        AMQP_PASSWORD: ${AMQP_SERVER_PASSWORD}
        AMQP_SERVER_CONCURRENCY: "2"
        AMQP_SERVER_MAX_CONCURRENCY: "2"
        AMQP_SERVER_SENDING_QUEUE_NAME: replyQueue
        AMQP_SERVER_SENDING_QUEUE_MAX_SIZE: 2047MB
        AMQP_SERVER_LISTENING_QUEUE_NAME: requestQueue
        AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE: 2047MB
        JOB_SERVICE_HOST: job-service
        JOB_SERVICE_PORT: 8080
        FILE_STORAGE_HOST: file-storage
        FILE_STORAGE_PORT: 8080
        TASK_PROCESSING_LIMIT: "2"
        TASK_PROCESSING_TIMEOUT_IN_MIN: "10"
      dockerfilePath: ./.docker/api-gateway/Dockerfile  # Assuming you have a Dockerfile for worker
