# render.yaml

services:
  # File Storage Database
  - name: file-storage-database
    type: database
    databaseType: postgresql
    plan: standard
    region: oregon
    disk:
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
      - key: POSTGRES_PASSWORD
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
      - key: POSTGRES_DB
        value: verapdfdb

  # File Storage Service
  - name: file-storage
    type: web
    env: docker
    docker:
      image: ghcr.io/verapdf/verapdf_file-storage:latest
    envVars:
      - key: LOCALSTORAGE_DATABASE_USERNAME
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
      - key: LOCALSTORAGE_DATABASE_PASSWORD
        value: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
      - key: LOCALSTORAGE_DATABASE_DB
        value: verapdfdb
      - key: LOCALSTORAGE_DATABASE_HOST
        value: file-storage-database
      - key: LOCALSTORAGE_DATABASE_PORT
        value: "5432"
      - key: LOCALSTORAGE_DISK_MIN_SPACE_THRESHOLD
        value: ${LOCAL_STORAGE_SERVICE_DISK_MIN_SPACE_THRESHOLD:-5GB}
      - key: LOCALSTORAGE_MAX_FILE_SIZE
        value: 100MB
      - key: LOCALSTORAGE_MAX_REQUEST_SIZE
        value: 101MB
    disk:
      sizeGB: 10
    ports:
      - 8080

  # Job Service Database
  - name: job-service-database
    type: database
    databaseType: postgresql
    plan: standard
    region: oregon
    disk:
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: ${JOB_SERVICE_DATABASE_USER}
      - key: POSTGRES_PASSWORD
        value: ${JOB_SERVICE_DATABASE_PASSWORD}
      - key: POSTGRES_DB
        value: verapdfjobdb

  # Job Service
  - name: job-service
    type: web
    env: docker
    docker:
      image: ghcr.io/verapdf/verapdf_job-service:latest
    envVars:
      - key: JOBSERVICE_DATABASE_USERNAME
        value: ${JOB_SERVICE_DATABASE_USER}
      - key: JOBSERVICE_DATABASE_PASSWORD
        value: ${JOB_SERVICE_DATABASE_PASSWORD}
      - key: JOBSERVICE_DATABASE_DB
        value: verapdfjobdb
      - key: JOBSERVICE_DATABASE_HOST
        value: job-service-database
      - key: JOBSERVICE_DATABASE_PORT
        value: "5432"
      - key: AMQP_SERVER_HOST
        value: queue
      - key: AMQP_USER
        value: ${AMQP_SERVER_USER}
      - key: AMQP_PASSWORD
        value: ${AMQP_SERVER_PASSWORD}
      - key: AMQP_SERVER_CONCURRENCY
        value: "4"
      - key: AMQP_SERVER_MAX_CONCURRENCY
        value: "8"
      - key: AMQP_SERVER_SENDING_QUEUE_NAME
        value: requestQueue
      - key: AMQP_SERVER_SENDING_QUEUE_MAX_SIZE
        value: 2047MB
      - key: AMQP_SERVER_LISTENING_QUEUE_NAME
        value: replyQueue
      - key: AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE
        value: 2047MB
      - key: TASK_PROCESSING_LIMIT
        value: "2"
    ports:
      - 8080

  # RabbitMQ Queue
  - name: queue
    type: web
    env: docker
    docker:
      image: rabbitmq:3.8.3
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: ${AMQP_SERVER_USER}
      - key: RABBITMQ_DEFAULT_PASSWORD
        value: ${AMQP_SERVER_PASSWORD}
    disk:
      sizeGB: 10
    ports:
      - 5672

  # Worker Service
  - name: worker
    type: web
    env: docker
    docker:
      image: ghcr.io/verapdf/verapdf_worker:latest
    envVars:
      - key: JVM_OPTS
        value: ${WORKER_JVM_OPTS}
      - key: AMQP_SERVER_HOST
        value: queue
      - key: AMQP_USER
        value: ${AMQP_SERVER_USER}
      - key: AMQP_PASSWORD
        value: ${AMQP_SERVER_PASSWORD}
      - key: AMQP_SERVER_CONCURRENCY
        value: "2"
      - key: AMQP_SERVER_MAX_CONCURRENCY
        value: "2"
      - key: AMQP_SERVER_SENDING_QUEUE_NAME
        value: replyQueue
      - key: AMQP_SERVER_SENDING_QUEUE_MAX_SIZE
        value: 2047MB
      - key: AMQP_SERVER_LISTENING_QUEUE_NAME
        value: requestQueue
      - key: AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE
        value: 2047MB
      - key: JOB_SERVICE_HOST
        value: job-service
      - key: JOB_SERVICE_PORT
        value: "8080"
      - key: FILE_STORAGE_HOST
        value: file-storage
      - key: FILE_STORAGE_PORT
        value: "8080"
      - key: TASK_PROCESSING_LIMIT
        value: "2"
      - key: TASK_PROCESSING_TIMEOUT_IN_MIN
        value: "10"
    ports:
      - 8080
